#!/bin/bash
# awk sed
jq -r '
  .name as $name |
  .height as $height |
  .weight as $weight |
  .types[0].type.name as $type |
  ($name | ascii_upcase[0:1] + .[1:]) as $name |
  ($type | ascii_upcase[0:1] + .[1:]) as $type |
  ($height / 10) as $formatted_height |
  ($weight / 10) as $formatted_weight |
  "\($name) is of type \($type), weighs \($formatted_weight)kg, and is \($formatted_height)m tall."
' data.json

# "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."