#!/bin/bash
# sed
CSV_FILE="pokemon_report.csv"

echo "Name,Height (m),Weight (kg)" > "${CSV_FILE}"

pokemon_list=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

for pokemon in "${pokemon_list[@]}"; do
    file="${pokemon}.json"
    jq -r '
        "\(.name),\(.height/10),\(.weight/10)"
    ' "$file" >> "$CSV_FILE"
done

echo "CSV Report generated at: $CSV_FILE"

cat pokemon_report.csv

awk -F, '
NR==1 { next }  # Skip header
{
    total_h += $2
    total_w += $3
    count++
}
END {
    printf "\nAverage Height: %.2f m\n", total_h/count
    printf "Average Weight: %.2f kg\n", total_w/count
}
' "$CSV_FILE"

